### ISSUE TITLE
increase css integration

### ISSUE THREAD

**Issue by yohji79** [JoomJunk/jj-discord#8]
hi, could you add this in your mod_discord.xml in order to have access to module class sfx in params

			<fieldset name="ADVANCED" label="your label">

				<field
					name="moduleclass_sfx"
					type="text"
					label="COM_MODULES_FIELD_MODULECLASS_SFX_LABEL"
					description="COM_MODULES_FIELD_MODULECLASS_SFX_DESC"
					icon="text_signature.png"
				/>
			</fieldset>

**Comment by C-Lodder** [comment]
Hi @yohji79

Thank you for reporting this. I've added the Module Class Suffix option and released another update:

https://joomjunk.co.uk/products/discord.html
